version: '3.9'

services:
  main_bot:
    build: .
    command: python main_bot.py
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app

  admin_bot:
    build: .
    command: python admin_bot.py
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
